export { AppContent } from "./AppContent";
export { Home } from "./Home";
export { Login } from "./Login"
export { Register } from "./Register"
export { ForgotPassword } from "./ForgotPassword"
export { NotFound } from "./NotFound"
export { PropertyDetails } from "./PropretyDetails";
export { Profile } from "./Profile";
export { AddProperty } from "./AddProperty";
